#ifndef SOCKET_STREAM_LIB__FILEDESC_CONFIG_H
#define SOCKET_STREAM_LIB__FILEDESC_CONFIG_H

#define _FILEDESC_VERSION_MAJOR 0 
#define _FILEDESC_VERSION_MINOR 1
#define _FILEDESC_SEPORATOR 

// Components defines
#define _FILEDESC_NETWORK_COMP

#define _FILEDESC_CONCAT1(_FILEDESC_X, _FILEDESC_Y) _FILEDESC_X##_FILEDESC_Y
#define _FILEDESC_CONCAT(_FILEDESC_X, _FILEDESC_Y) _FILEDESC_CONCAT1(_FILEDESC_X, _FILEDESC_Y)
#define _FILEDESC_VERSION _FILEDESC_CONCAT(_FILEDESC_VERSION_MAJOR, _FILEDESC_CONCAT(.,_FILEDESC_VERSION_MINOR))

#define _FILEDESC_NAMESPACE_BEGIN namespace filedesc { 
#define _FILEDESC_NAMESPACE_END }

#ifdef _FILEDESC_NETWORK_COMP
#define _FD_NETWORK_NAMESPACE_BEGIN namespace filedesc { namespace network {
#define _FD_NETWORK_NAMESPACE_END }}
#endif

#endif //SOCKET_STREAM_LIB__FILEDESC_CONFIG_H
